@extends('invoices.layout')

@php
    $docTitle = $invoice->type === 'quotation' ? 'Quotation' : 'Invoice';
@endphp

@section('title', ($invoice->title ?: $docTitle) . ' — ' . $invoice->reference)

@if ($invoice->title)
    @section('doc-heading', $invoice->title . ' — ' . $invoice->reference)
    @section('doc-custom-title', $invoice->title)
@else
    @section('doc-heading', $docTitle . ' — ' . $invoice->reference)
@endif

@php
    $canEdit = $invoice->canBeEditedBy(auth()->user());
    $pendingRequest = $invoice->latestEditRequest?->isPending() ? $invoice->latestEditRequest : null;
    $declinedRequest = (! $canEdit && ! $pendingRequest && $invoice->latestEditRequest?->status === 'declined') ? $invoice->latestEditRequest : null;
    $showRequestButton = ! $canEdit && ! $invoice->isAutoGenerated() && ! auth()->user()->isAdmin() && ! $pendingRequest;
@endphp

@section('toolbar')
    <a href="{{ route('admin.invoices.index') }}">&larr; Back to invoices</a>
    @if ($canEdit)
        <a href="{{ route('admin.invoices.edit', $invoice) }}">Edit</a>
    @elseif ($pendingRequest)
        <span class="toolbar-badge pending">Edit request pending</span>
    @elseif ($showRequestButton)
        <button type="button" onclick="document.getElementById('request-edit-modal').style.display='flex'">
            {{ $declinedRequest ? 'Request edit again' : 'Request edit' }}
        </button>
    @endif
    <a href="{{ route('admin.invoices.download', $invoice) }}">Download (customer copy)</a>
    @if (auth()->user()->isAdmin())
        <a href="{{ route('admin.invoices.download-internal', $invoice) }}" class="primary">Download (admin copy)</a>
    @endif
@endsection

@section('doc-title', $docTitle)
@section('doc-meta')
    Ref: {{ $invoice->reference }}<br>
    Date: {{ $invoice->created_at->format('d M Y') }}
@endsection

@section('content')
    @if ($declinedRequest)
        <div style="margin-bottom: 16px; padding: 10px 16px; background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; font-size: 12px; color: #991b1b;">
            Your edit request was declined{{ $declinedRequest->reviewedBy ? ' by ' . $declinedRequest->reviewedBy->name : '' }}. You can send a new request from the toolbar above.
        </div>
    @endif

    @if (auth()->user()->isAdmin() && $pendingRequest)
        <div style="margin-bottom: 16px; padding: 14px 16px; background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; font-size: 12px; color: #92400e;">
            <strong>{{ $pendingRequest->requestedBy?->name }}</strong> has requested to edit this document:
            <p style="margin: 6px 0; white-space: pre-line; color: #78350f;">{{ $pendingRequest->reason }}</p>
            <div style="display: flex; gap: 8px; margin-top: 8px;">
                <form method="POST" action="{{ route('admin.invoice-edit-requests.approve', $pendingRequest) }}">
                    @csrf
                    <button type="submit" style="border-radius: 6px; background: #1a7a35; color: #fff; padding: 6px 12px; font-size: 12px; font-weight: 600; border: none; cursor: pointer;">Approve</button>
                </form>
                <form method="POST" action="{{ route('admin.invoice-edit-requests.decline', $pendingRequest) }}">
                    @csrf
                    <button type="submit" style="border-radius: 6px; background: #ffffff; color: #991b1b; padding: 6px 12px; font-size: 12px; font-weight: 600; border: 1px solid #fecaca; cursor: pointer;">Decline</button>
                </form>
            </div>
        </div>
    @endif

    @include('invoices._body', [
        'billTo' => [
            'name' => $invoice->bill_to_name,
            'email' => $invoice->bill_to_email,
            'phone' => $invoice->bill_to_phone,
            'address' => $invoice->bill_to_address,
        ],
        'from' => config('app.name'),
        'lineItems' => $invoice->items->map(fn ($item) => [
            'description' => $item->description,
            'qty' => rtrim(rtrim(number_format($item->quantity, 2), '0'), '.'),
            'unitPrice' => (float) $item->unit_price,
            'actualPrice' => $item->actual_price !== null ? (float) $item->actual_price : null,
            'total' => (float) $item->total,
        ])->all(),
        'total' => (float) $invoice->total,
        'discount' => (float) $invoice->discount,
        'paymentInfo' => null,
        'notes' => $invoice->notes,
        'inspectionNotes' => $invoice->inspection_notes,
        'internal' => auth()->user()->isAdmin(),
    ])

    @if ($showRequestButton)
        <div id="request-edit-modal" style="display: none; position: fixed; inset: 0; z-index: 50; align-items: center; justify-content: center; padding: 16px; background: rgba(15, 23, 42, 0.5);">
            <div style="box-sizing: border-box; position: relative; width: 100%; max-width: 420px; border-radius: 16px; background: #ffffff; padding: 24px; box-shadow: 0 10px 30px rgba(0,0,0,0.2);">
                <button type="button" onclick="document.getElementById('request-edit-modal').style.display='none'" aria-label="Close" style="position: absolute; top: 12px; right: 12px; border: none; background: transparent; color: #94a3b8; cursor: pointer; padding: 4px; line-height: 0; border-radius: 8px;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>
                </button>
                <h3 style="margin: 0; padding-right: 24px; font-size: 15px; font-weight: 700; color: #0f172a;">Request edit access</h3>
                <p style="margin: 6px 0 0; font-size: 12px; color: #64748b;">Tell the admin why this document needs to change. You'll be able to edit it once approved.</p>
                <form method="POST" action="{{ route('admin.invoice-edit-requests.store', $invoice) }}" style="margin-top: 14px;">
                    @csrf
                    <textarea name="reason" required maxlength="1000" rows="4" placeholder="Reason for edit…" style="box-sizing: border-box; width: 100%; max-width: 100%; border: 1px solid #cbd5e1; border-radius: 8px; padding: 10px 12px; font-size: 13px; font-family: inherit; resize: vertical;"></textarea>
                    <div style="display: flex; justify-content: flex-end; gap: 8px; margin-top: 14px;">
                        <button type="button" onclick="document.getElementById('request-edit-modal').style.display='none'" style="border-radius: 8px; border: 1px solid #cbd5e1; background: #fff; color: #334155; padding: 8px 16px; font-size: 13px; font-weight: 600; cursor: pointer;">Cancel</button>
                        <button type="submit" style="border-radius: 8px; border: none; background: #1a7a35; color: #fff; padding: 8px 16px; font-size: 13px; font-weight: 600; cursor: pointer;">Send request</button>
                    </div>
                </form>
            </div>
        </div>
    @endif
@endsection
