<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Support\Str;

class Invoice extends Model
{
    public const TYPE_INVOICE = 'invoice';
    public const TYPE_QUOTATION = 'quotation';

    protected $fillable = [
        'type',
        'reference',
        'title',
        'invoiceable_type',
        'invoiceable_id',
        'consumer_id',
        'bill_to_name',
        'bill_to_email',
        'bill_to_phone',
        'bill_to_address',
        'inspection_notes',
        'total',
        'discount',
        'notes',
        'created_by',
        'unlocked_for_edit',
    ];

    protected function casts(): array
    {
        return [
            'total' => 'decimal:2',
            'discount' => 'decimal:2',
            'unlocked_for_edit' => 'boolean',
        ];
    }

    public function items(): HasMany
    {
        return $this->hasMany(InvoiceItem::class)->orderBy('sort_order');
    }

    public function invoiceable(): MorphTo
    {
        return $this->morphTo();
    }

    public function consumer(): BelongsTo
    {
        return $this->belongsTo(User::class, 'consumer_id');
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function editRequests(): HasMany
    {
        return $this->hasMany(InvoiceEditRequest::class);
    }

    public function latestEditRequest(): HasOne
    {
        return $this->hasOne(InvoiceEditRequest::class)->latestOfMany();
    }

    public function isQuotation(): bool
    {
        return $this->type === self::TYPE_QUOTATION;
    }

    /** Auto-generated from a Booking on completion — never editable/deletable by anyone. */
    public function isAutoGenerated(): bool
    {
        return $this->invoiceable_type !== null;
    }

    /**
     * Admins can always edit manual documents; quotations are always free for staff to edit;
     * a manual invoice is only editable by staff once an edit request has been approved, and
     * that approval is consumed the moment the edit is saved (see InvoiceController::update()).
     */
    public function canBeEditedBy(User $user): bool
    {
        if ($this->isAutoGenerated()) {
            return false;
        }

        if ($user->isAdmin()) {
            return true;
        }

        if ($this->isQuotation()) {
            return true;
        }

        return (bool) $this->unlocked_for_edit;
    }

    public function hasPendingEditRequest(): bool
    {
        return $this->editRequests()->where('status', InvoiceEditRequest::STATUS_PENDING)->exists();
    }

    public static function generateReference(string $type): string
    {
        $prefix = $type === self::TYPE_QUOTATION ? 'QUO' : 'INV';

        do {
            $ref = $prefix . '-' . strtoupper(Str::random(6));
        } while (static::where('reference', $ref)->exists());

        return $ref;
    }
}
