<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Invoice;
use App\Models\InvoiceEditRequest;
use App\Services\Notifier;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class InvoiceEditRequestController extends Controller
{
    public function store(Request $request, Invoice $invoice): RedirectResponse
    {
        abort_if($invoice->isQuotation(), 403, 'Quotations can be edited directly, no request needed.');
        abort_if($invoice->isAutoGenerated(), 403, 'Auto-generated documents cannot be edited.');
        abort_if($request->user()->isAdmin(), 403, 'Admins can edit documents directly.');
        abort_unless($invoice->created_by === $request->user()->id, 403, 'You can only request edits on documents you created.');

        if ($invoice->unlocked_for_edit) {
            return back()->with('error', 'This document is already unlocked for editing.');
        }

        if ($invoice->hasPendingEditRequest()) {
            return back()->with('error', 'You already have a pending edit request for this document.');
        }

        $data = $request->validate([
            'reason' => ['required', 'string', 'max:1000'],
        ]);

        InvoiceEditRequest::create([
            'invoice_id' => $invoice->id,
            'requested_by' => $request->user()->id,
            'reason' => $data['reason'],
            'status' => InvoiceEditRequest::STATUS_PENDING,
        ]);

        app(Notifier::class)->notifyAdmins(
            'invoice_edit_request',
            'Invoice edit requested',
            $request->user()->name . ' wants to edit ' . $invoice->reference . '.',
            route('admin.invoices.index')
        );

        return back()->with('success', 'Edit request sent to admin.');
    }

    public function approve(Request $request, InvoiceEditRequest $editRequest): RedirectResponse
    {
        abort_unless($request->user()->isAdmin(), 403);

        if ($editRequest->isPending()) {
            $editRequest->update([
                'status' => InvoiceEditRequest::STATUS_APPROVED,
                'reviewed_by' => $request->user()->id,
                'reviewed_at' => now(),
            ]);

            $editRequest->invoice()->update(['unlocked_for_edit' => true]);

            app(Notifier::class)->notify(
                $editRequest->requestedBy,
                'invoice_edit_request',
                'Edit request approved',
                'You can now edit ' . $editRequest->invoice->reference . '.',
                route('admin.invoices.show', $editRequest->invoice_id)
            );
        }

        return back()->with('success', 'Edit request approved.');
    }

    public function decline(Request $request, InvoiceEditRequest $editRequest): RedirectResponse
    {
        abort_unless($request->user()->isAdmin(), 403);

        if ($editRequest->isPending()) {
            $editRequest->update([
                'status' => InvoiceEditRequest::STATUS_DECLINED,
                'reviewed_by' => $request->user()->id,
                'reviewed_at' => now(),
            ]);

            app(Notifier::class)->notify(
                $editRequest->requestedBy,
                'invoice_edit_request',
                'Edit request declined',
                'Your request to edit ' . $editRequest->invoice->reference . ' was declined.',
                route('admin.invoices.show', $editRequest->invoice_id)
            );
        }

        return back()->with('success', 'Edit request declined.');
    }
}
